package alex.orobynskyi.niprices.domain.models.games

data class Doc(
    val _version_: Long,
    val age_rating_sorting_i: Int,
    val age_rating_type: String,
    val age_rating_value: String,
    val change_date: String,
    val cloud_saves_b: Boolean,
    val club_nintendo: Boolean,
    val compatible_controller: List<String>,
    val copyright_s: String,
    val date_from: String,
    val dates_released_dts: List<String>,
    val digital_version_b: Boolean,
    val excerpt: String,
    val fs_id: String,
    val game_categories_txt: List<String>,
    val game_category: List<String>,
    val gift_finder_carousel_image_url_s: String,
    val gift_finder_detail_page_image_url_s: String,
    val gift_finder_wishlist_image_url_s: String,
    val hits_i: Int,
    val image_url: String,
    val image_url_h2x1_s: String,
    val image_url_sq_s: String,
    val language_availability: List<String>,
    val nsuid_txt: List<String>,
    val originally_for_t: String,
    val paid_subscription_required_b: Boolean,
    val pg_s: String,
    val physical_version_b: Boolean,
    val play_mode_handheld_mode_b: Boolean,
    val play_mode_tabletop_mode_b: Boolean,
    val play_mode_tv_mode_b: Boolean,
    val playable_on_txt: List<String>,
    val players_from: Int,
    val players_to: Int,
    val pretty_agerating_s: String,
    val pretty_date_s: String,
    val pretty_game_categories_txt: List<String>,
    val price_discount_percentage_f: Double,
    val price_has_discount_b: Boolean,
    val price_lowest_f: Double,
    val price_sorting_f: Double,
    val product_code_ss: List<String>,
    val product_code_txt: List<String>,
    val publisher: String,
    val sorting_title: String,
    val switch_game_voucher_b: Boolean,
    val system_names_txt: List<String>,
    val system_type: List<String>,
    val title: String,
    val title_extras_txt: List<String>,
    val type: String,
    val url: String,
    val voice_chat_b: Boolean,
    val wishlist_email_banner460w_image_url_s: String,
    val wishlist_email_banner640w_image_url_s: String,
    val wishlist_email_square_image_url_s: String


) {
    override fun toString(): String {
        return "Doc(_version_=$_version_, age_rating_sorting_i=$age_rating_sorting_i, age_rating_type='$age_rating_type', age_rating_value='$age_rating_value', change_date='$change_date', cloud_saves_b=$cloud_saves_b, club_nintendo=$club_nintendo, compatible_controller=$compatible_controller, copyright_s='$copyright_s', date_from='$date_from', dates_released_dts=$dates_released_dts, digital_version_b=$digital_version_b, excerpt='$excerpt', fs_id='$fs_id', game_categories_txt=$game_categories_txt, game_category=$game_category, gift_finder_carousel_image_url_s='$gift_finder_carousel_image_url_s', gift_finder_detail_page_image_url_s='$gift_finder_detail_page_image_url_s', gift_finder_wishlist_image_url_s='$gift_finder_wishlist_image_url_s', hits_i=$hits_i, image_url='$image_url', image_url_h2x1_s='$image_url_h2x1_s', image_url_sq_s='$image_url_sq_s', language_availability=$language_availability, nsuid_txt=$nsuid_txt, originally_for_t='$originally_for_t', paid_subscription_required_b=$paid_subscription_required_b, pg_s='$pg_s', physical_version_b=$physical_version_b, play_mode_handheld_mode_b=$play_mode_handheld_mode_b, play_mode_tabletop_mode_b=$play_mode_tabletop_mode_b, play_mode_tv_mode_b=$play_mode_tv_mode_b, playable_on_txt=$playable_on_txt, players_from=$players_from, players_to=$players_to, pretty_agerating_s='$pretty_agerating_s', pretty_date_s='$pretty_date_s', pretty_game_categories_txt=$pretty_game_categories_txt, price_discount_percentage_f=$price_discount_percentage_f, price_has_discount_b=$price_has_discount_b, price_lowest_f=$price_lowest_f, price_sorting_f=$price_sorting_f, product_code_ss=$product_code_ss, product_code_txt=$product_code_txt, publisher='$publisher', sorting_title='$sorting_title', switch_game_voucher_b=$switch_game_voucher_b, system_names_txt=$system_names_txt, system_type=$system_type, title='$title', title_extras_txt=$title_extras_txt, type='$type', url='$url', voice_chat_b=$voice_chat_b, wishlist_email_banner460w_image_url_s='$wishlist_email_banner460w_image_url_s', wishlist_email_banner640w_image_url_s='$wishlist_email_banner640w_image_url_s', wishlist_email_square_image_url_s='$wishlist_email_square_image_url_s')"
    }
}